export const employeeRanges = ['1-10', '11-20', '21-50', '51-100', '100-200', '200-300', '300+'];
export const jobLocations = ['onsite', 'remotely', 'hybrid'];
export const workingTimes = ['part-time', 'full-time'];
export const seniorityLevels = ['Junior', 'Mid-Level', 'Senior', 'Team-Lead', 'CTO'];
export const status = ['online', 'offline'];
export const roles= ['user', 'company_HR']
export const technicalSkills= [
    'JavaScript',
    'Python',
    'Java',
    'C#',
    'C++',
    'Ruby',
    'HTML/CSS',
    'SQL',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Django',
    'Flask',
    'Spring Boot',
    'Kotlin',
    'Swift',
    'Objective-C',
    'PHP',
    'Perl',
    'Go',
    'Rust',
    'TypeScript',
    'MATLAB',
    'R',
    'Scala',
    'Haskell',
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Ansible',
    'Jenkins',
    'Git',
    'Linux',
    'Windows Server',
    'Networking',
    'Cybersecurity',
    'Machine Learning',
    'Data Science',
    'Big Data',
    'Blockchain',
    'DevOps',
    'Agile/Scrum',
    'CI/CD',
    'IoT',
    'AR/VR'
]
export const softSkills= [
    'Communication',
    'Teamwork',
    'Problem Solving',
    'Time Management',
    'Adaptability',
    'Critical Thinking',
    'Conflict Resolution',
    'Leadership',
    'Creativity',
    'Work Ethic',
    'Attention to Detail',
    'Interpersonal Skills',
    'Emotional Intelligence',
    'Negotiation',
    'Networking',
    'Public Speaking',
    'Decision Making',
    'Stress Management',
    'Empathy',
    'Patience',
    'Collaboration',
    'Motivation',
    'Active Listening',
    'Flexibility',
    'Dependability',
    'Self-motivation',
    'Open-mindedness',
    'Resilience',
    'Persuasion',
    'Strategic Thinking'
]